[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo run build --filter=$APP_NAME..."]

[start]
cmd = "pnpm --filter=$APP_NAME start"