import type { Product } from '@luxe-maison/core';

export const womenCatalogProducts: Product[] = [
  {
    id: 'wmn-001',
    name: 'Silk Embroidered Punjabi',
    price: 179,
    originalPrice: 219,
    section: 'women',
    category: 'punjabi',
    fit: 'regular',
    fabric: 'silk',
    season: 'all-season',
    colors: [
      { name: 'Rose', hex: '#E8B4B8' },
      { name: 'Ivory', hex: '#F5F0E8' },
      { name: 'Emerald', hex: '#046307' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80',
      'https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=800&q=80',
    ],
    description:
      'An elegant silk Punjabi with delicate hand embroidery along the neckline and cuffs, designed for festive occasions and refined celebrations.',
    details: ['100% Mulberry Silk', 'Hand-embroidered neckline', 'Side slits', 'Dry clean only'],
    badge: 'Bestseller',
    rating: 4.9,
    reviews: 76,
  },
  {
    id: 'wmn-002',
    name: 'Linen Resort Shirt',
    price: 139,
    section: 'women',
    category: 'shirt',
    fit: 'relaxed',
    fabric: 'linen',
    season: 'summer',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Blush', hex: '#F4C2C2' },
      { name: 'Sage', hex: '#8B9D83' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
    ],
    description:
      'A breezy linen shirt with a relaxed silhouette and subtle texture, perfect for warm days and effortless layering.',
    details: ['100% European Linen', 'Relaxed fit', 'Mother-of-pearl buttons', 'Machine wash cold'],
    badge: 'New Arrival',
    rating: 4.7,
    reviews: 52,
  },
  {
    id: 'wmn-003',
    name: 'Premium Cotton Tee',
    price: 59,
    section: 'women',
    category: 'tshirt',
    fit: 'slim',
    fabric: 'cotton',
    season: 'all-season',
    colors: [
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Cream', hex: '#FFFDD0' },
      { name: 'Taupe', hex: '#8B7D6B' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
    ],
    description:
      'A soft, fitted cotton tee with a clean neckline and refined drape — an everyday essential elevated with premium fabric.',
    details: ['100% Organic Cotton', 'Slim fit', 'Reinforced seams', 'Machine washable'],
    rating: 4.6,
    reviews: 118,
  },
  {
    id: 'wmn-004',
    name: 'Wide Leg Linen Trousers',
    price: 149,
    section: 'women',
    category: 'pants',
    fit: 'relaxed',
    fabric: 'linen',
    season: 'summer',
    colors: [
      { name: 'Sand', hex: '#D2B48C' },
      { name: 'Black', hex: '#1A1A1A' },
      { name: 'Olive', hex: '#556B2F' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80',
    ],
    description:
      'Flowing wide-leg trousers in breathable linen with a high waist and tailored finish for polished warm-weather dressing.',
    details: ['100% Linen', 'High-rise waist', 'Side pockets', 'Machine wash cold'],
    badge: 'Premium',
    rating: 4.8,
    reviews: 64,
  },
  {
    id: 'wmn-005',
    name: 'Heritage Cotton Punjabi',
    price: 119,
    section: 'women',
    category: 'punjabi',
    fit: 'relaxed',
    fabric: 'cotton',
    season: 'summer',
    colors: [
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Lavender', hex: '#E6E6FA' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: [
      'https://images.unsplash.com/photo-1608234807905-4466023792f5?w=800&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
    ],
    description:
      'A lightweight cotton Punjabi with a relaxed cut and subtle tonal stitching, designed for comfort without sacrificing elegance.',
    details: ['100% Organic Cotton', 'Relaxed fit', 'Breathable weave', 'Machine washable'],
    rating: 4.5,
    reviews: 41,
  },
];

export const kidsCatalogProducts: Product[] = [
  {
    id: 'kid-001',
    name: 'Junior Cotton Punjabi',
    price: 79,
    section: 'kids',
    category: 'punjabi',
    fit: 'regular',
    fabric: 'cotton',
    season: 'all-season',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'Mint', hex: '#98FF98' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: [
      'https://images.unsplash.com/photo-1608234807905-4466023792f5?w=800&q=80',
      'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80',
    ],
    description:
      'A soft cotton Punjabi tailored for young celebrants, with gentle seams and easy movement for all-day wear.',
    details: ['100% Cotton', 'Soft interior finish', 'Easy-care fabric', 'Machine washable'],
    badge: 'Bestseller',
    rating: 4.8,
    reviews: 93,
  },
  {
    id: 'kid-002',
    name: 'Kids Linen Shirt',
    price: 69,
    section: 'kids',
    category: 'shirt',
    fit: 'regular',
    fabric: 'linen',
    season: 'summer',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Light Blue', hex: '#ADD8E6' },
      { name: 'Khaki', hex: '#C3B091' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
    ],
    description:
      'Breathable linen shirt with a classic collar and durable stitching, made for warm days and special occasions alike.',
    details: ['Linen-cotton blend', 'Reinforced buttons', 'Comfortable fit', 'Machine washable'],
    badge: 'New Arrival',
    rating: 4.6,
    reviews: 47,
  },
  {
    id: 'kid-003',
    name: 'Playday Cotton Tee',
    price: 39,
    section: 'kids',
    category: 'tshirt',
    fit: 'relaxed',
    fabric: 'cotton',
    season: 'all-season',
    colors: [
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Red', hex: '#C41E3A' },
      { name: 'Green', hex: '#228B22' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80',
    ],
    description:
      'A durable everyday tee in ultra-soft cotton, designed to keep up with active days while staying comfortable.',
    details: ['100% Cotton', 'Tagless label', 'Pre-shrunk', 'Machine washable'],
    rating: 4.7,
    reviews: 132,
  },
  {
    id: 'kid-004',
    name: 'School Formal Shirt',
    price: 59,
    section: 'kids',
    category: 'shirt',
    fit: 'slim',
    fabric: 'cotton',
    season: 'all-season',
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Light Blue', hex: '#ADD8E6' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80',
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80',
    ],
    description:
      'A crisp cotton formal shirt with a neat collar and easy-iron finish, ideal for school and ceremonies.',
    details: ['Easy-iron cotton', 'Button-down collar', 'Reinforced cuffs', 'Machine washable'],
    rating: 4.5,
    reviews: 58,
  },
  {
    id: 'kid-005',
    name: 'Comfort Chinos',
    price: 69,
    section: 'kids',
    category: 'pants',
    fit: 'regular',
    fabric: 'cotton',
    season: 'all-season',
    colors: [
      { name: 'Tan', hex: '#D2B48C' },
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Grey', hex: '#808080' },
    ],
    sizes: ['4Y', '6Y', '8Y', '10Y', '12Y'],
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&q=80',
    ],
    description:
      'Soft stretch chinos with an adjustable waist and durable construction for everyday school and weekend wear.',
    details: ['Cotton twill with stretch', 'Adjustable waist', 'Reinforced knees', 'Machine washable'],
    badge: 'Essential',
    rating: 4.6,
    reviews: 71,
  },
];
