/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as rolesManagerRouteRouteImport } from './routes/(roles)/manager/route'
import { Route as rolesEmployeeRouteRouteImport } from './routes/(roles)/employee/route'
import { Route as rolesAdminRouteRouteImport } from './routes/(roles)/admin/route'
import { Route as rolesManagerIndexRouteImport } from './routes/(roles)/manager/index'
import { Route as rolesEmployeeIndexRouteImport } from './routes/(roles)/employee/index'
import { Route as rolesAdminIndexRouteImport } from './routes/(roles)/admin/index'
import { Route as rolesManagerNewsletterRouteImport } from './routes/(roles)/manager/newsletter'
import { Route as rolesManagerDiscountsRouteImport } from './routes/(roles)/manager/discounts'
import { Route as rolesManagerDashboardRouteImport } from './routes/(roles)/manager/dashboard'
import { Route as rolesManagerCampaignsRouteImport } from './routes/(roles)/manager/campaigns'
import { Route as rolesManagerAnalyticsRouteImport } from './routes/(roles)/manager/analytics'
import { Route as rolesEmployeeDashboardRouteImport } from './routes/(roles)/employee/dashboard'
import { Route as rolesAdminTeamRouteImport } from './routes/(roles)/admin/team'
import { Route as rolesAdminSettingsRouteImport } from './routes/(roles)/admin/settings'
import { Route as rolesAdminPopupRouteImport } from './routes/(roles)/admin/popup'
import { Route as rolesAdminNewsletterRouteImport } from './routes/(roles)/admin/newsletter'
import { Route as rolesAdminHomepageRouteImport } from './routes/(roles)/admin/homepage'
import { Route as rolesAdminDiscountsRouteImport } from './routes/(roles)/admin/discounts'
import { Route as rolesAdminDashboardRouteImport } from './routes/(roles)/admin/dashboard'
import { Route as rolesAdminCampaignsRouteImport } from './routes/(roles)/admin/campaigns'
import { Route as rolesAdminAnalyticsRouteImport } from './routes/(roles)/admin/analytics'
import { Route as rolesAdminAccessControlRouteImport } from './routes/(roles)/admin/access-control'
import { Route as rolesManagerOrdersIndexRouteImport } from './routes/(roles)/manager/orders/index'
import { Route as rolesManagerCustomersIndexRouteImport } from './routes/(roles)/manager/customers/index'
import { Route as rolesEmployeeProductsIndexRouteImport } from './routes/(roles)/employee/products/index'
import { Route as rolesEmployeeOrdersIndexRouteImport } from './routes/(roles)/employee/orders/index'
import { Route as rolesEmployeeCustomersIndexRouteImport } from './routes/(roles)/employee/customers/index'
import { Route as rolesAdminProductsIndexRouteImport } from './routes/(roles)/admin/products/index'
import { Route as rolesAdminOrdersIndexRouteImport } from './routes/(roles)/admin/orders/index'
import { Route as rolesAdminCustomersIndexRouteImport } from './routes/(roles)/admin/customers/index'
import { Route as rolesManagerOrdersIdRouteImport } from './routes/(roles)/manager/orders/$id'
import { Route as rolesManagerCustomersIdRouteImport } from './routes/(roles)/manager/customers/$id'
import { Route as rolesEmployeeOrdersIdRouteImport } from './routes/(roles)/employee/orders/$id'
import { Route as rolesEmployeeCustomersIdRouteImport } from './routes/(roles)/employee/customers/$id'
import { Route as rolesAdminProductsNewRouteImport } from './routes/(roles)/admin/products/new'
import { Route as rolesAdminPagesSlugRouteImport } from './routes/(roles)/admin/pages/$slug'
import { Route as rolesAdminOrdersIdRouteImport } from './routes/(roles)/admin/orders/$id'
import { Route as rolesAdminCustomersIdRouteImport } from './routes/(roles)/admin/customers/$id'
import { Route as rolesAdminProductsIdEditRouteImport } from './routes/(roles)/admin/products/$id.edit'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const rolesManagerRouteRoute = rolesManagerRouteRouteImport.update({
  id: '/(roles)/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const rolesEmployeeRouteRoute = rolesEmployeeRouteRouteImport.update({
  id: '/(roles)/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const rolesAdminRouteRoute = rolesAdminRouteRouteImport.update({
  id: '/(roles)/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const rolesManagerIndexRoute = rolesManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesEmployeeIndexRoute = rolesEmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rolesEmployeeRouteRoute,
} as any)
const rolesAdminIndexRoute = rolesAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesManagerNewsletterRoute = rolesManagerNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerDiscountsRoute = rolesManagerDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerDashboardRoute = rolesManagerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerCampaignsRoute = rolesManagerCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerAnalyticsRoute = rolesManagerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesEmployeeDashboardRoute = rolesEmployeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rolesEmployeeRouteRoute,
} as any)
const rolesAdminTeamRoute = rolesAdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminSettingsRoute = rolesAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminPopupRoute = rolesAdminPopupRouteImport.update({
  id: '/popup',
  path: '/popup',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminNewsletterRoute = rolesAdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminHomepageRoute = rolesAdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminDiscountsRoute = rolesAdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminDashboardRoute = rolesAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminCampaignsRoute = rolesAdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminAnalyticsRoute = rolesAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminAccessControlRoute = rolesAdminAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesManagerOrdersIndexRoute = rolesManagerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerCustomersIndexRoute =
  rolesManagerCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => rolesManagerRouteRoute,
  } as any)
const rolesEmployeeProductsIndexRoute =
  rolesEmployeeProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => rolesEmployeeRouteRoute,
  } as any)
const rolesEmployeeOrdersIndexRoute =
  rolesEmployeeOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => rolesEmployeeRouteRoute,
  } as any)
const rolesEmployeeCustomersIndexRoute =
  rolesEmployeeCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => rolesEmployeeRouteRoute,
  } as any)
const rolesAdminProductsIndexRoute = rolesAdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminOrdersIndexRoute = rolesAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminCustomersIndexRoute =
  rolesAdminCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => rolesAdminRouteRoute,
  } as any)
const rolesManagerOrdersIdRoute = rolesManagerOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesManagerCustomersIdRoute = rolesManagerCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rolesManagerRouteRoute,
} as any)
const rolesEmployeeOrdersIdRoute = rolesEmployeeOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rolesEmployeeRouteRoute,
} as any)
const rolesEmployeeCustomersIdRoute =
  rolesEmployeeCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => rolesEmployeeRouteRoute,
  } as any)
const rolesAdminProductsNewRoute = rolesAdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminPagesSlugRoute = rolesAdminPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminOrdersIdRoute = rolesAdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminCustomersIdRoute = rolesAdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rolesAdminRouteRoute,
} as any)
const rolesAdminProductsIdEditRoute =
  rolesAdminProductsIdEditRouteImport.update({
    id: '/products/$id/edit',
    path: '/products/$id/edit',
    getParentRoute: () => rolesAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof rolesAdminRouteRouteWithChildren
  '/employee': typeof rolesEmployeeRouteRouteWithChildren
  '/manager': typeof rolesManagerRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/admin/access-control': typeof rolesAdminAccessControlRoute
  '/admin/analytics': typeof rolesAdminAnalyticsRoute
  '/admin/campaigns': typeof rolesAdminCampaignsRoute
  '/admin/dashboard': typeof rolesAdminDashboardRoute
  '/admin/discounts': typeof rolesAdminDiscountsRoute
  '/admin/homepage': typeof rolesAdminHomepageRoute
  '/admin/newsletter': typeof rolesAdminNewsletterRoute
  '/admin/popup': typeof rolesAdminPopupRoute
  '/admin/settings': typeof rolesAdminSettingsRoute
  '/admin/team': typeof rolesAdminTeamRoute
  '/employee/dashboard': typeof rolesEmployeeDashboardRoute
  '/manager/analytics': typeof rolesManagerAnalyticsRoute
  '/manager/campaigns': typeof rolesManagerCampaignsRoute
  '/manager/dashboard': typeof rolesManagerDashboardRoute
  '/manager/discounts': typeof rolesManagerDiscountsRoute
  '/manager/newsletter': typeof rolesManagerNewsletterRoute
  '/admin/': typeof rolesAdminIndexRoute
  '/employee/': typeof rolesEmployeeIndexRoute
  '/manager/': typeof rolesManagerIndexRoute
  '/admin/customers/$id': typeof rolesAdminCustomersIdRoute
  '/admin/orders/$id': typeof rolesAdminOrdersIdRoute
  '/admin/pages/$slug': typeof rolesAdminPagesSlugRoute
  '/admin/products/new': typeof rolesAdminProductsNewRoute
  '/employee/customers/$id': typeof rolesEmployeeCustomersIdRoute
  '/employee/orders/$id': typeof rolesEmployeeOrdersIdRoute
  '/manager/customers/$id': typeof rolesManagerCustomersIdRoute
  '/manager/orders/$id': typeof rolesManagerOrdersIdRoute
  '/admin/customers/': typeof rolesAdminCustomersIndexRoute
  '/admin/orders/': typeof rolesAdminOrdersIndexRoute
  '/admin/products/': typeof rolesAdminProductsIndexRoute
  '/employee/customers/': typeof rolesEmployeeCustomersIndexRoute
  '/employee/orders/': typeof rolesEmployeeOrdersIndexRoute
  '/employee/products/': typeof rolesEmployeeProductsIndexRoute
  '/manager/customers/': typeof rolesManagerCustomersIndexRoute
  '/manager/orders/': typeof rolesManagerOrdersIndexRoute
  '/admin/products/$id/edit': typeof rolesAdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/admin/access-control': typeof rolesAdminAccessControlRoute
  '/admin/analytics': typeof rolesAdminAnalyticsRoute
  '/admin/campaigns': typeof rolesAdminCampaignsRoute
  '/admin/dashboard': typeof rolesAdminDashboardRoute
  '/admin/discounts': typeof rolesAdminDiscountsRoute
  '/admin/homepage': typeof rolesAdminHomepageRoute
  '/admin/newsletter': typeof rolesAdminNewsletterRoute
  '/admin/popup': typeof rolesAdminPopupRoute
  '/admin/settings': typeof rolesAdminSettingsRoute
  '/admin/team': typeof rolesAdminTeamRoute
  '/employee/dashboard': typeof rolesEmployeeDashboardRoute
  '/manager/analytics': typeof rolesManagerAnalyticsRoute
  '/manager/campaigns': typeof rolesManagerCampaignsRoute
  '/manager/dashboard': typeof rolesManagerDashboardRoute
  '/manager/discounts': typeof rolesManagerDiscountsRoute
  '/manager/newsletter': typeof rolesManagerNewsletterRoute
  '/admin': typeof rolesAdminIndexRoute
  '/employee': typeof rolesEmployeeIndexRoute
  '/manager': typeof rolesManagerIndexRoute
  '/admin/customers/$id': typeof rolesAdminCustomersIdRoute
  '/admin/orders/$id': typeof rolesAdminOrdersIdRoute
  '/admin/pages/$slug': typeof rolesAdminPagesSlugRoute
  '/admin/products/new': typeof rolesAdminProductsNewRoute
  '/employee/customers/$id': typeof rolesEmployeeCustomersIdRoute
  '/employee/orders/$id': typeof rolesEmployeeOrdersIdRoute
  '/manager/customers/$id': typeof rolesManagerCustomersIdRoute
  '/manager/orders/$id': typeof rolesManagerOrdersIdRoute
  '/admin/customers': typeof rolesAdminCustomersIndexRoute
  '/admin/orders': typeof rolesAdminOrdersIndexRoute
  '/admin/products': typeof rolesAdminProductsIndexRoute
  '/employee/customers': typeof rolesEmployeeCustomersIndexRoute
  '/employee/orders': typeof rolesEmployeeOrdersIndexRoute
  '/employee/products': typeof rolesEmployeeProductsIndexRoute
  '/manager/customers': typeof rolesManagerCustomersIndexRoute
  '/manager/orders': typeof rolesManagerOrdersIndexRoute
  '/admin/products/$id/edit': typeof rolesAdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(roles)/admin': typeof rolesAdminRouteRouteWithChildren
  '/(roles)/employee': typeof rolesEmployeeRouteRouteWithChildren
  '/(roles)/manager': typeof rolesManagerRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(roles)/admin/access-control': typeof rolesAdminAccessControlRoute
  '/(roles)/admin/analytics': typeof rolesAdminAnalyticsRoute
  '/(roles)/admin/campaigns': typeof rolesAdminCampaignsRoute
  '/(roles)/admin/dashboard': typeof rolesAdminDashboardRoute
  '/(roles)/admin/discounts': typeof rolesAdminDiscountsRoute
  '/(roles)/admin/homepage': typeof rolesAdminHomepageRoute
  '/(roles)/admin/newsletter': typeof rolesAdminNewsletterRoute
  '/(roles)/admin/popup': typeof rolesAdminPopupRoute
  '/(roles)/admin/settings': typeof rolesAdminSettingsRoute
  '/(roles)/admin/team': typeof rolesAdminTeamRoute
  '/(roles)/employee/dashboard': typeof rolesEmployeeDashboardRoute
  '/(roles)/manager/analytics': typeof rolesManagerAnalyticsRoute
  '/(roles)/manager/campaigns': typeof rolesManagerCampaignsRoute
  '/(roles)/manager/dashboard': typeof rolesManagerDashboardRoute
  '/(roles)/manager/discounts': typeof rolesManagerDiscountsRoute
  '/(roles)/manager/newsletter': typeof rolesManagerNewsletterRoute
  '/(roles)/admin/': typeof rolesAdminIndexRoute
  '/(roles)/employee/': typeof rolesEmployeeIndexRoute
  '/(roles)/manager/': typeof rolesManagerIndexRoute
  '/(roles)/admin/customers/$id': typeof rolesAdminCustomersIdRoute
  '/(roles)/admin/orders/$id': typeof rolesAdminOrdersIdRoute
  '/(roles)/admin/pages/$slug': typeof rolesAdminPagesSlugRoute
  '/(roles)/admin/products/new': typeof rolesAdminProductsNewRoute
  '/(roles)/employee/customers/$id': typeof rolesEmployeeCustomersIdRoute
  '/(roles)/employee/orders/$id': typeof rolesEmployeeOrdersIdRoute
  '/(roles)/manager/customers/$id': typeof rolesManagerCustomersIdRoute
  '/(roles)/manager/orders/$id': typeof rolesManagerOrdersIdRoute
  '/(roles)/admin/customers/': typeof rolesAdminCustomersIndexRoute
  '/(roles)/admin/orders/': typeof rolesAdminOrdersIndexRoute
  '/(roles)/admin/products/': typeof rolesAdminProductsIndexRoute
  '/(roles)/employee/customers/': typeof rolesEmployeeCustomersIndexRoute
  '/(roles)/employee/orders/': typeof rolesEmployeeOrdersIndexRoute
  '/(roles)/employee/products/': typeof rolesEmployeeProductsIndexRoute
  '/(roles)/manager/customers/': typeof rolesManagerCustomersIndexRoute
  '/(roles)/manager/orders/': typeof rolesManagerOrdersIndexRoute
  '/(roles)/admin/products/$id/edit': typeof rolesAdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/forgot-password'
    | '/login'
    | '/admin/access-control'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/admin/settings'
    | '/admin/team'
    | '/employee/dashboard'
    | '/manager/analytics'
    | '/manager/campaigns'
    | '/manager/dashboard'
    | '/manager/discounts'
    | '/manager/newsletter'
    | '/admin/'
    | '/employee/'
    | '/manager/'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/pages/$slug'
    | '/admin/products/new'
    | '/employee/customers/$id'
    | '/employee/orders/$id'
    | '/manager/customers/$id'
    | '/manager/orders/$id'
    | '/admin/customers/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/employee/customers/'
    | '/employee/orders/'
    | '/employee/products/'
    | '/manager/customers/'
    | '/manager/orders/'
    | '/admin/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/admin/access-control'
    | '/admin/analytics'
    | '/admin/campaigns'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/homepage'
    | '/admin/newsletter'
    | '/admin/popup'
    | '/admin/settings'
    | '/admin/team'
    | '/employee/dashboard'
    | '/manager/analytics'
    | '/manager/campaigns'
    | '/manager/dashboard'
    | '/manager/discounts'
    | '/manager/newsletter'
    | '/admin'
    | '/employee'
    | '/manager'
    | '/admin/customers/$id'
    | '/admin/orders/$id'
    | '/admin/pages/$slug'
    | '/admin/products/new'
    | '/employee/customers/$id'
    | '/employee/orders/$id'
    | '/manager/customers/$id'
    | '/manager/orders/$id'
    | '/admin/customers'
    | '/admin/orders'
    | '/admin/products'
    | '/employee/customers'
    | '/employee/orders'
    | '/employee/products'
    | '/manager/customers'
    | '/manager/orders'
    | '/admin/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(roles)/admin'
    | '/(roles)/employee'
    | '/(roles)/manager'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(roles)/admin/access-control'
    | '/(roles)/admin/analytics'
    | '/(roles)/admin/campaigns'
    | '/(roles)/admin/dashboard'
    | '/(roles)/admin/discounts'
    | '/(roles)/admin/homepage'
    | '/(roles)/admin/newsletter'
    | '/(roles)/admin/popup'
    | '/(roles)/admin/settings'
    | '/(roles)/admin/team'
    | '/(roles)/employee/dashboard'
    | '/(roles)/manager/analytics'
    | '/(roles)/manager/campaigns'
    | '/(roles)/manager/dashboard'
    | '/(roles)/manager/discounts'
    | '/(roles)/manager/newsletter'
    | '/(roles)/admin/'
    | '/(roles)/employee/'
    | '/(roles)/manager/'
    | '/(roles)/admin/customers/$id'
    | '/(roles)/admin/orders/$id'
    | '/(roles)/admin/pages/$slug'
    | '/(roles)/admin/products/new'
    | '/(roles)/employee/customers/$id'
    | '/(roles)/employee/orders/$id'
    | '/(roles)/manager/customers/$id'
    | '/(roles)/manager/orders/$id'
    | '/(roles)/admin/customers/'
    | '/(roles)/admin/orders/'
    | '/(roles)/admin/products/'
    | '/(roles)/employee/customers/'
    | '/(roles)/employee/orders/'
    | '/(roles)/employee/products/'
    | '/(roles)/manager/customers/'
    | '/(roles)/manager/orders/'
    | '/(roles)/admin/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  rolesAdminRouteRoute: typeof rolesAdminRouteRouteWithChildren
  rolesEmployeeRouteRoute: typeof rolesEmployeeRouteRouteWithChildren
  rolesManagerRouteRoute: typeof rolesManagerRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(roles)/manager': {
      id: '/(roles)/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof rolesManagerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(roles)/employee': {
      id: '/(roles)/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof rolesEmployeeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(roles)/admin': {
      id: '/(roles)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof rolesAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(roles)/manager/': {
      id: '/(roles)/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof rolesManagerIndexRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/employee/': {
      id: '/(roles)/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof rolesEmployeeIndexRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/admin/': {
      id: '/(roles)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof rolesAdminIndexRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/manager/newsletter': {
      id: '/(roles)/manager/newsletter'
      path: '/newsletter'
      fullPath: '/manager/newsletter'
      preLoaderRoute: typeof rolesManagerNewsletterRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/discounts': {
      id: '/(roles)/manager/discounts'
      path: '/discounts'
      fullPath: '/manager/discounts'
      preLoaderRoute: typeof rolesManagerDiscountsRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/dashboard': {
      id: '/(roles)/manager/dashboard'
      path: '/dashboard'
      fullPath: '/manager/dashboard'
      preLoaderRoute: typeof rolesManagerDashboardRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/campaigns': {
      id: '/(roles)/manager/campaigns'
      path: '/campaigns'
      fullPath: '/manager/campaigns'
      preLoaderRoute: typeof rolesManagerCampaignsRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/analytics': {
      id: '/(roles)/manager/analytics'
      path: '/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof rolesManagerAnalyticsRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/employee/dashboard': {
      id: '/(roles)/employee/dashboard'
      path: '/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof rolesEmployeeDashboardRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/admin/team': {
      id: '/(roles)/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof rolesAdminTeamRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/settings': {
      id: '/(roles)/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof rolesAdminSettingsRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/popup': {
      id: '/(roles)/admin/popup'
      path: '/popup'
      fullPath: '/admin/popup'
      preLoaderRoute: typeof rolesAdminPopupRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/newsletter': {
      id: '/(roles)/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof rolesAdminNewsletterRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/homepage': {
      id: '/(roles)/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof rolesAdminHomepageRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/discounts': {
      id: '/(roles)/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof rolesAdminDiscountsRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/dashboard': {
      id: '/(roles)/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof rolesAdminDashboardRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/campaigns': {
      id: '/(roles)/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof rolesAdminCampaignsRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/analytics': {
      id: '/(roles)/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof rolesAdminAnalyticsRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/access-control': {
      id: '/(roles)/admin/access-control'
      path: '/access-control'
      fullPath: '/admin/access-control'
      preLoaderRoute: typeof rolesAdminAccessControlRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/manager/orders/': {
      id: '/(roles)/manager/orders/'
      path: '/orders'
      fullPath: '/manager/orders/'
      preLoaderRoute: typeof rolesManagerOrdersIndexRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/customers/': {
      id: '/(roles)/manager/customers/'
      path: '/customers'
      fullPath: '/manager/customers/'
      preLoaderRoute: typeof rolesManagerCustomersIndexRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/employee/products/': {
      id: '/(roles)/employee/products/'
      path: '/products'
      fullPath: '/employee/products/'
      preLoaderRoute: typeof rolesEmployeeProductsIndexRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/employee/orders/': {
      id: '/(roles)/employee/orders/'
      path: '/orders'
      fullPath: '/employee/orders/'
      preLoaderRoute: typeof rolesEmployeeOrdersIndexRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/employee/customers/': {
      id: '/(roles)/employee/customers/'
      path: '/customers'
      fullPath: '/employee/customers/'
      preLoaderRoute: typeof rolesEmployeeCustomersIndexRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/admin/products/': {
      id: '/(roles)/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof rolesAdminProductsIndexRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/orders/': {
      id: '/(roles)/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof rolesAdminOrdersIndexRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/customers/': {
      id: '/(roles)/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof rolesAdminCustomersIndexRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/manager/orders/$id': {
      id: '/(roles)/manager/orders/$id'
      path: '/orders/$id'
      fullPath: '/manager/orders/$id'
      preLoaderRoute: typeof rolesManagerOrdersIdRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/manager/customers/$id': {
      id: '/(roles)/manager/customers/$id'
      path: '/customers/$id'
      fullPath: '/manager/customers/$id'
      preLoaderRoute: typeof rolesManagerCustomersIdRouteImport
      parentRoute: typeof rolesManagerRouteRoute
    }
    '/(roles)/employee/orders/$id': {
      id: '/(roles)/employee/orders/$id'
      path: '/orders/$id'
      fullPath: '/employee/orders/$id'
      preLoaderRoute: typeof rolesEmployeeOrdersIdRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/employee/customers/$id': {
      id: '/(roles)/employee/customers/$id'
      path: '/customers/$id'
      fullPath: '/employee/customers/$id'
      preLoaderRoute: typeof rolesEmployeeCustomersIdRouteImport
      parentRoute: typeof rolesEmployeeRouteRoute
    }
    '/(roles)/admin/products/new': {
      id: '/(roles)/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof rolesAdminProductsNewRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/pages/$slug': {
      id: '/(roles)/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof rolesAdminPagesSlugRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/orders/$id': {
      id: '/(roles)/admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof rolesAdminOrdersIdRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/customers/$id': {
      id: '/(roles)/admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof rolesAdminCustomersIdRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
    '/(roles)/admin/products/$id/edit': {
      id: '/(roles)/admin/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/admin/products/$id/edit'
      preLoaderRoute: typeof rolesAdminProductsIdEditRouteImport
      parentRoute: typeof rolesAdminRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface rolesAdminRouteRouteChildren {
  rolesAdminAccessControlRoute: typeof rolesAdminAccessControlRoute
  rolesAdminAnalyticsRoute: typeof rolesAdminAnalyticsRoute
  rolesAdminCampaignsRoute: typeof rolesAdminCampaignsRoute
  rolesAdminDashboardRoute: typeof rolesAdminDashboardRoute
  rolesAdminDiscountsRoute: typeof rolesAdminDiscountsRoute
  rolesAdminHomepageRoute: typeof rolesAdminHomepageRoute
  rolesAdminNewsletterRoute: typeof rolesAdminNewsletterRoute
  rolesAdminPopupRoute: typeof rolesAdminPopupRoute
  rolesAdminSettingsRoute: typeof rolesAdminSettingsRoute
  rolesAdminTeamRoute: typeof rolesAdminTeamRoute
  rolesAdminIndexRoute: typeof rolesAdminIndexRoute
  rolesAdminCustomersIdRoute: typeof rolesAdminCustomersIdRoute
  rolesAdminOrdersIdRoute: typeof rolesAdminOrdersIdRoute
  rolesAdminPagesSlugRoute: typeof rolesAdminPagesSlugRoute
  rolesAdminProductsNewRoute: typeof rolesAdminProductsNewRoute
  rolesAdminCustomersIndexRoute: typeof rolesAdminCustomersIndexRoute
  rolesAdminOrdersIndexRoute: typeof rolesAdminOrdersIndexRoute
  rolesAdminProductsIndexRoute: typeof rolesAdminProductsIndexRoute
  rolesAdminProductsIdEditRoute: typeof rolesAdminProductsIdEditRoute
}

const rolesAdminRouteRouteChildren: rolesAdminRouteRouteChildren = {
  rolesAdminAccessControlRoute: rolesAdminAccessControlRoute,
  rolesAdminAnalyticsRoute: rolesAdminAnalyticsRoute,
  rolesAdminCampaignsRoute: rolesAdminCampaignsRoute,
  rolesAdminDashboardRoute: rolesAdminDashboardRoute,
  rolesAdminDiscountsRoute: rolesAdminDiscountsRoute,
  rolesAdminHomepageRoute: rolesAdminHomepageRoute,
  rolesAdminNewsletterRoute: rolesAdminNewsletterRoute,
  rolesAdminPopupRoute: rolesAdminPopupRoute,
  rolesAdminSettingsRoute: rolesAdminSettingsRoute,
  rolesAdminTeamRoute: rolesAdminTeamRoute,
  rolesAdminIndexRoute: rolesAdminIndexRoute,
  rolesAdminCustomersIdRoute: rolesAdminCustomersIdRoute,
  rolesAdminOrdersIdRoute: rolesAdminOrdersIdRoute,
  rolesAdminPagesSlugRoute: rolesAdminPagesSlugRoute,
  rolesAdminProductsNewRoute: rolesAdminProductsNewRoute,
  rolesAdminCustomersIndexRoute: rolesAdminCustomersIndexRoute,
  rolesAdminOrdersIndexRoute: rolesAdminOrdersIndexRoute,
  rolesAdminProductsIndexRoute: rolesAdminProductsIndexRoute,
  rolesAdminProductsIdEditRoute: rolesAdminProductsIdEditRoute,
}

const rolesAdminRouteRouteWithChildren = rolesAdminRouteRoute._addFileChildren(
  rolesAdminRouteRouteChildren,
)

interface rolesEmployeeRouteRouteChildren {
  rolesEmployeeDashboardRoute: typeof rolesEmployeeDashboardRoute
  rolesEmployeeIndexRoute: typeof rolesEmployeeIndexRoute
  rolesEmployeeCustomersIdRoute: typeof rolesEmployeeCustomersIdRoute
  rolesEmployeeOrdersIdRoute: typeof rolesEmployeeOrdersIdRoute
  rolesEmployeeCustomersIndexRoute: typeof rolesEmployeeCustomersIndexRoute
  rolesEmployeeOrdersIndexRoute: typeof rolesEmployeeOrdersIndexRoute
  rolesEmployeeProductsIndexRoute: typeof rolesEmployeeProductsIndexRoute
}

const rolesEmployeeRouteRouteChildren: rolesEmployeeRouteRouteChildren = {
  rolesEmployeeDashboardRoute: rolesEmployeeDashboardRoute,
  rolesEmployeeIndexRoute: rolesEmployeeIndexRoute,
  rolesEmployeeCustomersIdRoute: rolesEmployeeCustomersIdRoute,
  rolesEmployeeOrdersIdRoute: rolesEmployeeOrdersIdRoute,
  rolesEmployeeCustomersIndexRoute: rolesEmployeeCustomersIndexRoute,
  rolesEmployeeOrdersIndexRoute: rolesEmployeeOrdersIndexRoute,
  rolesEmployeeProductsIndexRoute: rolesEmployeeProductsIndexRoute,
}

const rolesEmployeeRouteRouteWithChildren =
  rolesEmployeeRouteRoute._addFileChildren(rolesEmployeeRouteRouteChildren)

interface rolesManagerRouteRouteChildren {
  rolesManagerAnalyticsRoute: typeof rolesManagerAnalyticsRoute
  rolesManagerCampaignsRoute: typeof rolesManagerCampaignsRoute
  rolesManagerDashboardRoute: typeof rolesManagerDashboardRoute
  rolesManagerDiscountsRoute: typeof rolesManagerDiscountsRoute
  rolesManagerNewsletterRoute: typeof rolesManagerNewsletterRoute
  rolesManagerIndexRoute: typeof rolesManagerIndexRoute
  rolesManagerCustomersIdRoute: typeof rolesManagerCustomersIdRoute
  rolesManagerOrdersIdRoute: typeof rolesManagerOrdersIdRoute
  rolesManagerCustomersIndexRoute: typeof rolesManagerCustomersIndexRoute
  rolesManagerOrdersIndexRoute: typeof rolesManagerOrdersIndexRoute
}

const rolesManagerRouteRouteChildren: rolesManagerRouteRouteChildren = {
  rolesManagerAnalyticsRoute: rolesManagerAnalyticsRoute,
  rolesManagerCampaignsRoute: rolesManagerCampaignsRoute,
  rolesManagerDashboardRoute: rolesManagerDashboardRoute,
  rolesManagerDiscountsRoute: rolesManagerDiscountsRoute,
  rolesManagerNewsletterRoute: rolesManagerNewsletterRoute,
  rolesManagerIndexRoute: rolesManagerIndexRoute,
  rolesManagerCustomersIdRoute: rolesManagerCustomersIdRoute,
  rolesManagerOrdersIdRoute: rolesManagerOrdersIdRoute,
  rolesManagerCustomersIndexRoute: rolesManagerCustomersIndexRoute,
  rolesManagerOrdersIndexRoute: rolesManagerOrdersIndexRoute,
}

const rolesManagerRouteRouteWithChildren =
  rolesManagerRouteRoute._addFileChildren(rolesManagerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  rolesAdminRouteRoute: rolesAdminRouteRouteWithChildren,
  rolesEmployeeRouteRoute: rolesEmployeeRouteRouteWithChildren,
  rolesManagerRouteRoute: rolesManagerRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
